# Generated by Django 4.0 on 2024-09-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=350)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
    ]
