# Generated by Django 4.2.8 on 2024-09-17 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_categorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=150)),
                ('img', models.ImageField(upload_to='api/images/')),
                ('prefix', models.CharField(max_length=150)),
                ('url_doc', models.CharField(max_length=800)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categorias')),
            ],
            options={
                'verbose_name_plural': 'Maquinas',
            },
        ),
    ]
