# Generated by Django 4.2.8 on 2024-09-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='api/pdfs/'),
        ),
    ]
