# Generated by Django 4.2.8 on 2024-10-09 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_maquina_url_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='primer_ejemplo',
        ),
        migrations.AddField(
            model_name='comentario',
            name='publicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='api.publicacion'),
        ),
    ]
