# Generated by Django 4.2.8 on 2024-11-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_comentario_primer_ejemplo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='pdf_especificaciones_tecnicas',
            field=models.FileField(blank=True, null=True, upload_to='api/pdfs/'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='pdf_plano_electrico',
            field=models.FileField(blank=True, null=True, upload_to='api/pdfs/'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='pdf_plano_hidraulico',
            field=models.FileField(blank=True, null=True, upload_to='api/pdfs/'),
        ),
    ]
